
model:
    pretrain: checkpoints/pt/TSF-B/lavila_best.pth
    freeze_vis_backbone: true
    freeze_txt_backbone: true
    tune_bias: true

data:
    dataset: egtea
    root: /data/EGTEA/cropped_clips
    metadata: /data/EGTEA/train_split1.txt
    metadata_val: /data/EGTEA/test_split1.txt
    clip_length: 16
    clip_stride: 2

training:
    lr: 0.0001
    batch_size: 4
    epoch: 10
    use_checkpoint: false
    save_freq: 10
    eval_freq: 2

exp: ft/sp1_bias
