
model:
    pretrain: checkpoints/pt/TSF-B/lavila_epo1.pth
    freeze_vis_backbone: true
    freeze_txt_backbone: true
    text_prompt:
        n_ctx: 8
    visual_prompt:
        num_layers: 12
        prompt_dim: 768
        num_tokens: 128
        deep: true
        deep_shared: false
        split_st: false
        pt_spt: true
        pt_tmp: false
        style: default
        st: 0   # prompt tuning starting from st-th layer (default: first layer)
        end: 12 # prompt tuning starting from end-th layer (default: last layer)

data:
    dataset: charades_ego
    root: /data/CharadesEgo/CharadesEgo_v1_480
    metadata: /data/CharadesEgo/CharadesEgo/metadata_filtered_train.pkl # all the training data
    metadata_val: /data/CharadesEgo/CharadesEgo/CharadesEgo_v1_test_only1st.csv
    clip_length: 16
    sparse_sample: true

training:
    lr: 0.01
    batch_size: 4
    epoch: 10
    use_checkpoint: true
    save_freq: 10
    eval_freq: 1

exp: prompt/vop
